# Generated by Django 4.1.7 on 2023-03-02 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ds_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ManyToManyField(related_name='inventory_items', to='ds_bot.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='ds_bot.discorduser'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
