# Generated by Django 4.1.7 on 2023-03-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds_bot', '0002_delete_name_remove_item_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='ds_bot.item'),
            preserve_default=False,
        ),
    ]
