# Generated by Django 4.1.7 on 2023-03-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds_bot', '0004_remove_inventory_item_remove_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory settings', 'verbose_name_plural': 'Auth inventory'},
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='ds_bot.discorduser'),
        ),
    ]
