# Generated by Django 4.1.7 on 2023-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_bot', '0005_alter_inventory_options_alter_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory settings', 'verbose_name_plural': 'indicate inventory'},
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
