# Generated by Django 4.1.7 on 2023-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_bot', '0006_alter_inventory_options_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
